type Channel =
	| "main"
	| "homeTimeline"
	| "localTimeline"
	| "hybridTimeline"
	| "globalTimeline"
	| "notesStats"
	| "serverStats"
	| "userList"
	| "messaging"
	| "messagingIndex"
	| "drive"
	| "hashtag"
	| "gamesReversi"
	| "gamesReversiGame"
export default Channel
