name: Validate renovate.json

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  renovate-config-validator:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Validate renovate.json
        run: renovate-config-validator
