name: Check schema diff

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate schema
        run: npm run schema

      - name: Check diff
        run: git diff --exit-code config-schema.json
